export type Language =
  | 'hi'
  | 'en'
  | 'pa'
  | 'mr'
  | 'gu'
  | 'te'
  | 'ta'
  | 'bn'
  | 'kn'
  | 'ml'
  | 'or'
  | 'as'
  | 'ur'
  | 'mai'
  | 'ks'
  | 'kok'
  | 'ne'

export interface LanguageOption {
  code: Language
  label: string
  nativeName: string
  region: string
  flag: string
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी', region: 'UP, MP, Bihar, Raj, Har', flag: '🌾' },
  { code: 'en', label: 'English', nativeName: 'English', region: 'Pan-India', flag: '🌐' },
  { code: 'pa', label: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab, Haryana', flag: '🌾' },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra', flag: '🌾' },
  { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat', flag: '🌾' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra & Telangana', flag: '🌾' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu', flag: '🌾' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal', flag: '🌾' },
  { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka', flag: '🌾' },
  { code: 'ml', label: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala', flag: '🌾' },
  { code: 'or', label: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha', flag: '🌾' },
  { code: 'as', label: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam', flag: '🌾' },
  { code: 'ur', label: 'Urdu', nativeName: 'اردو', region: 'J&K, Telangana, UP', flag: '🌾' },
  { code: 'mai', label: 'Maithili', nativeName: 'मैथिली', region: 'Bihar, Mithila', flag: '🌾' },
  { code: 'ks', label: 'Kashmiri', nativeName: 'कॉशुर', region: 'Jammu & Kashmir', flag: '🌾' },
  { code: 'kok', label: 'Konkani', nativeName: 'कोंकणी', region: 'Goa, Coastal', flag: '🌾' },
  { code: 'ne', label: 'Nepali', nativeName: 'नेपाली', region: 'Sikkim, Hills', flag: '🌾' },
]

type TranslationKey = keyof typeof translations.en

const translations = {
  en: {
    dashboard: 'Dashboard', produce: 'Produce', market: 'Market', buyers: 'Buyers', buyerPortal: 'Buyer Portal', storage: 'Storage', processing: 'Processing', assistant: 'Assistant', analytics: 'Analytics',
    farmerWorkspace: 'FARMER WORKSPACE', logout: 'Log out', closeMenu: 'Close menu', openMenu: 'Open menu',
    farmerOverview: 'Farmer overview', goodToSeeYou: 'Good to see you', dashboardIntro: 'A clear view of what your harvest can do next.', harvestIntelligence: 'Harvest intelligence', harvestTagline: "Turn today's harvest into tomorrow's stronger decision.",
    nextAction: 'What should you do next?', totalProduce: 'Total Produce', estimatedValue: 'Estimated Value', potentialProfit: 'Potential Profit', wastageRisk: 'Wastage Risk', activeRecommendations: 'Active Recommendations', availableBuyers: 'Available Buyers', yourProduce: 'Your Produce', addProduce: 'Add produce', viewAll: 'View all', noProduce: "You haven't added any produce yet.", entriesOnRecord: 'entries on record.',
    loading: 'Loading…', loadingProduce: 'Loading your produce…', addProduceTitle: 'Add Produce', editProduce: 'Edit Produce', crop: 'Crop', quantity: 'Quantity', unit: 'Unit', quality: 'Quality', harvestDate: 'Harvest date', location: 'Location', expectedSellDate: 'Expected selling date', optional: 'optional', saveChanges: 'Save changes', saving: 'Saving…', addFirstEntry: 'Add your first entry →', viewEdit: 'View / Edit', getRecommendation: 'Get Recommendation', findBuyers: 'Find Buyers', processingOptions: 'Processing Options', delete: 'Delete', deleteConfirm: 'Delete this produce entry?', harvested: 'Harvested', backToProduce: 'Back to Produce', recommendation: 'Recommendation', recommendedAction: 'Recommended Action', score: 'Score', profit: 'Profit', risk: 'Risk', estimatedData: 'All figures are estimated from demo market, storage, processing, and buyer data — not live prices.', matchingBuyers: 'Matching Buyers', noMatchingBuyers: 'No buyers currently want this much of this crop.', proposeTransaction: 'Propose Transaction', proposing: 'Proposing…', alreadySold: 'Produce already sold', processingOpportunities: 'Processing Opportunities', noProcessingCrop: 'No processing units accept this crop yet.', inputQuantity: 'Input Quantity', expectedOutput: 'Expected Output', estimatedRevenue: 'Estimated Revenue', potentialProfitLabel: 'Potential Profit',
    marketPrices: 'Market Prices', useMyLocation: 'Use my location', findingLocation: 'Finding location…', livePriceNote: 'Live prices are sourced from AGMARKNET when configured; demo rows are labelled below.', humidity: 'Humidity', wind: 'Wind', noPriceData: 'No price data for this crop yet.', mandiRateFeed: 'Mandi rate feed', live: 'Live', demo: 'Demo', marketColumn: 'Market', distance: 'Distance', currentPrice: 'Current Price', previousPrice: 'Previous Price', change: 'Change', demand: 'Demand',
    buyersTitle: 'Buyer Marketplace', buyerNote: 'Demo buyer postings for hackathon demonstration.', noBuyers: 'No buyer postings yet.', lookingFor: 'Looking for', upTo: 'Up to',
    storageTitle: 'Storage Finder', storageNote: 'Demo storage facilities for hackathon demonstration.', noStorage: 'No storage facilities available.', suitableFor: 'Suitable for', available: 'available', away: 'away',
    processingTitle: 'Turn Produce into Value', processingNote: 'Demo processing units for hackathon demonstration.', noProcessing: 'No processing units available.', processingCost: 'processing cost',
    askAgriFlow: 'Ask AgriFlow', tryAsking: 'Try asking:', aiResponse: 'AI response', quickAnswer: 'Quick answer', thinking: 'Thinking…', send: 'Send', askQuestion: 'Ask a question', responseLanguage: 'Response language',
    analyticsOverview: 'Performance overview', farmNumbers: 'Your farm, in numbers', analyticsIntro: 'See where value is being created across your produce, prices, and transactions.', liveActivity: 'Live from your activity', wastageAvoided: 'Wastage avoided', valueProtected: 'Value protected', transactions: 'Transactions', completedProposals: 'Completed proposals', transactionValue: 'Transaction value', totalRealized: 'Total realized value', farmStory: 'Your farm story starts here', analyticsEmpty: 'Add produce and check its recommendations to start seeing charts here.', low: 'Low', medium: 'Medium', high: 'High', dashboardNextAction: 'Check your recommendations to decide your next move.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'Location access is not available in this browser.', locationDenied: 'Location permission was denied. You can enable it in browser settings.', weatherUnavailable: 'Could not load weather for your location.',
    autoDetectRegion: 'Auto-detect (Region)', regionDetected: 'Region detected',
  },
  hi: {
    dashboard: 'डैशबोर्ड', produce: 'उपज', market: 'बाज़ार', buyers: 'खरीदार', buyerPortal: 'खरीदार पोर्टल', storage: 'भंडारण', processing: 'प्रसंस्करण', assistant: 'सहायक', analytics: 'विश्लेषण',
    farmerWorkspace: 'किसान कार्यक्षेत्र', logout: 'लॉग आउट', closeMenu: 'मेनू बंद करें', openMenu: 'मेनू खोलें',
    farmerOverview: 'किसान अवलोकन', goodToSeeYou: 'नमस्ते', dashboardIntro: 'आपकी फसल और उपज का संपूर्ण विवरण।', harvestIntelligence: 'फसल की जानकारी', harvestTagline: 'आज की फसल से कल का बेहतर निर्णय लें।',
    nextAction: 'अब आपको क्या करना चाहिए?', totalProduce: 'कुल उपज', estimatedValue: 'अनुमानित मूल्य', potentialProfit: 'संभावित लाभ', wastageRisk: 'बर्बादी का जोखिम', activeRecommendations: 'सक्रिय सुझाव', availableBuyers: 'उपलब्ध खरीदार', yourProduce: 'आपकी उपज', addProduce: 'उपज जोड़ें', viewAll: 'सभी देखें', noProduce: 'आपने अभी तक कोई उपज नहीं जोड़ी है।', entriesOnRecord: 'प्रविष्टियां दर्ज हैं।',
    loading: 'लोड हो रहा है…', loadingProduce: 'आपकी उपज लोड हो रही है…', addProduceTitle: 'उपज जोड़ें', editProduce: 'उपज संपादित करें', crop: 'फसल', quantity: 'मात्रा', unit: 'इकाई', quality: 'गुणवत्ता', harvestDate: 'कटाई की तारीख', location: 'स्थान', expectedSellDate: 'अपेक्षित बिक्री तारीख', optional: 'वैकल्पिक', saveChanges: 'बदलाव सहेजें', saving: 'सहेज रहे हैं…', addFirstEntry: 'पहली प्रविष्टि जोड़ें →', viewEdit: 'देखें / संपादित करें', getRecommendation: 'सुझाव पाएं', findBuyers: 'खरीदार खोजें', processingOptions: 'प्रसंस्करण विकल्प', delete: 'हटाएं', deleteConfirm: 'क्या यह उपज प्रविष्टि हटानी है?', harvested: 'कटाई', backToProduce: 'उपज पर वापस जाएं', recommendation: 'सुझाव', recommendedAction: 'अनुशंसित कार्रवाई', score: 'स्कोर', profit: 'लाभ', risk: 'जोखिम', estimatedData: 'सभी आंकड़े डेमो बाज़ार, भंडारण, प्रसंस्करण और खरीदार डेटा से अनुमानित हैं, लाइव भाव नहीं।', matchingBuyers: 'मिलान वाले खरीदार', noMatchingBuyers: 'अभी कोई खरीदार इस फसल की इतनी मात्रा नहीं चाहता।', proposeTransaction: 'लेनदेन प्रस्तावित करें', proposing: 'प्रस्ताव भेज रहे हैं…', alreadySold: 'उपज पहले ही बिक चुकी है', processingOpportunities: 'प्रसंस्करण अवसर', noProcessingCrop: 'अभी कोई प्रसंस्करण इकाई इस फसल को स्वीकार नहीं करती।', inputQuantity: 'इनपुट मात्रा', expectedOutput: 'अनुमानित आउटपुट', estimatedRevenue: 'अनुमानित आय', potentialProfitLabel: 'संभावित लाभ',
    marketPrices: 'बाज़ार भाव', useMyLocation: 'मेरा स्थान इस्तेमाल करें', findingLocation: 'स्थान खोज रहे हैं…', livePriceNote: 'लाइव भाव उपलब्ध होने पर AGMARKNET से लिए जाते हैं; डेमो भाव नीचे बताए गए हैं।', humidity: 'नमी', wind: 'हवा', noPriceData: 'इस फसल के लिए अभी भाव उपलब्ध नहीं हैं।', mandiRateFeed: 'मंडी भाव', live: 'लाइव', demo: 'डेमो', marketColumn: 'बाज़ार', distance: 'दूरी', currentPrice: 'वर्तमान भाव', previousPrice: 'पिछला भाव', change: 'बदलाव', demand: 'मांग',
    buyersTitle: 'खरीदार बाज़ार', buyerNote: 'प्रदर्शन के लिए डेमो खरीदार पोस्टिंग।', noBuyers: 'अभी कोई खरीदार पोस्टिंग नहीं है।', lookingFor: 'चाहिए', upTo: 'अधिकतम',
    storageTitle: 'भंडारण खोजें', storageNote: 'प्रदर्शन के लिए डेमो भंडारण सुविधाएं।', noStorage: 'भंडारण सुविधा उपलब्ध नहीं है।', suitableFor: 'उपयुक्त फसलें', available: 'उपलब्ध', away: 'दूर',
    processingTitle: 'उपज से मूल्य बनाएं', processingNote: 'प्रदर्शन के लिए डेमो प्रसंस्करण इकाइयां।', noProcessing: 'प्रसंस्करण इकाई उपलब्ध नहीं है।', processingCost: 'प्रसंस्करण लागत',
    askAgriFlow: 'AgriFlow से पूछें', tryAsking: 'पूछकर देखें:', aiResponse: 'AI उत्तर', quickAnswer: 'त्वरित उत्तर', thinking: 'सोच रहे हैं…', send: 'भेजें', askQuestion: 'सवाल पूछें', responseLanguage: 'उत्तर की भाषा',
    analyticsOverview: 'प्रदर्शन अवलोकन', farmNumbers: 'आपका खेत, आंकड़ों में', analyticsIntro: 'अपनी उपज, भाव और लेनदेन से बन रहे मूल्य को देखें।', liveActivity: 'आपकी गतिविधि से लाइव', wastageAvoided: 'बर्बादी से बचाया', valueProtected: 'सुरक्षित मूल्य', transactions: 'लेनदेन', completedProposals: 'पूरे प्रस्ताव', transactionValue: 'लेनदेन मूल्य', totalRealized: 'कुल प्राप्त मूल्य', farmStory: 'आपके खेत की कहानी यहां से शुरू होती है', analyticsEmpty: 'चार्ट देखने के लिए उपज जोड़ें और उसके सुझाव देखें।', low: 'कम', medium: 'मध्यम', high: 'अधिक', dashboardNextAction: 'अपने अगले कदम का निर्णय लेने के लिए सुझाव देखें।',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'इस ब्राउज़र में स्थान सुविधा उपलब्ध नहीं है।', locationDenied: 'स्थान की अनुमति नहीं मिली। इसे ब्राउज़र सेटिंग्स में चालू करें।', weatherUnavailable: 'आपके स्थान का मौसम लोड नहीं हो सका।',
    autoDetectRegion: 'स्वचालित (क्षेत्र अनुसार)', regionDetected: 'पहचाना गया क्षेत्र',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ', produce: 'ਫ਼ਸਲ', market: 'ਮੰਡੀ', buyers: 'ਖਰੀਦਦਾਰ', buyerPortal: 'ਖਰੀਦਦਾਰ ਪੋਰਟਲ', storage: 'ਸਟੋਰੇਜ', processing: 'ਪ੍ਰੋਸੈਸਿੰਗ', assistant: 'ਸਹਾਇਕ', analytics: 'ਅੰਕੜੇ',
    farmerWorkspace: 'ਕਿਸਾਨ ਵਰਕਸਪੇਸ', logout: 'ਲਾਗ ਆਉਟ', closeMenu: 'ਮੀਨੂ ਬੰਦ ਕਰੋ', openMenu: 'ਮੀਨੂ ਖੋਲ੍ਹੋ',
    farmerOverview: 'ਕਿਸਾਨ ਸੰਖੇਪ', goodToSeeYou: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', dashboardIntro: 'ਤੁਹਾਡੀ ਫ਼ਸਲ ਅਤੇ ਉਪਜ ਦਾ ਪੂਰਾ ਵੇਰਵਾ।', harvestIntelligence: 'ਫ਼ਸਲ ਜਾਣਕਾਰੀ', harvestTagline: 'ਅੱਜ ਦੀ ਵਾਢੀ ਨਾਲ ਕੱਲ੍ਹ ਦਾ ਬਿਹਤਰ ਫੈਸਲਾ ਲਓ।',
    nextAction: 'ਅੱਗੇ ਕੀ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?', totalProduce: 'ਕੁੱਲ ਉਪਜ', estimatedValue: 'ਅੰਦਾਜ਼ਨ ਮੁੱਲ', potentialProfit: 'ਸੰਭਾਵਿਤ ਮੁਨਾਫ਼ਾ', wastageRisk: 'ਖ਼ਰਾਬੀ ਦਾ ਖ਼ਤਰਾ', activeRecommendations: 'ਸਰਗਰਮ ਸਿਫ਼ਾਰਸ਼ਾਂ', availableBuyers: 'ਮੌਜੂਦ ਖਰੀਦਦਾਰ', yourProduce: 'ਤੁਹਾਡੀ ਉਪਜ', addProduce: 'ਉਪਜ ਸ਼ਾਮਲ ਕਰੋ', viewAll: 'ਸਾਰੇ ਵੇਖੋ', noProduce: 'ਤੁਸੀਂ ਅਜੇ ਕੋਈ ਉਪਜ ਸ਼ਾਮਲ ਨਹੀਂ ਕੀਤੀ।', entriesOnRecord: 'ਰਿਕਾਰਡ ਦਰਜ ਹਨ।',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…', loadingProduce: 'ਉਪਜ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…', addProduceTitle: 'ਉਪਜ ਜੋੜੋ', editProduce: 'ਉਪਜ ਬਦਲੋ', crop: 'ਫ਼ਸਲ', quantity: 'ਮਾਤਰਾ', unit: 'ਇਕਾਈ', quality: 'ਗੁਣਵੱਤਾ', harvestDate: 'ਵਾਢੀ ਦੀ ਮਿਤੀ', location: 'ਸਥਾਨ', expectedSellDate: 'ਵੇਚਣ ਦੀ ਮਿਤੀ', optional: 'ਵਿਕਲਪਿਕ', saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ', saving: 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…', addFirstEntry: 'ਪਹਿਲੀ ਫ਼ਸਲ ਸ਼ਾਮਲ ਕਰੋ →', viewEdit: 'ਵੇਖੋ / ਸੋਧੋ', getRecommendation: 'ਸਿਫ਼ਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ', findBuyers: 'ਖਰੀਦਦਾਰ ਲੱਭੋ', processingOptions: 'ਪ੍ਰੋਸੈਸਿੰਗ ਵਿਕਲਪ', delete: 'ਮਿਟਾਓ', deleteConfirm: 'ਕੀ ਇਹ ਉਪਜ ਹਟਾਉਣੀ ਹੈ?', harvested: 'ਕਟਾਈ', backToProduce: 'ਉਪਜ ਤੇ ਵਾਪਸ ਜਾਓ', recommendation: 'ਸਿਫ਼ਾਰਸ਼', recommendedAction: 'ਸਿਫ਼ਾਰਸ਼ੀ ਕਾਰਵਾਈ', score: 'ਸਕੋਰ', profit: 'ਮੁਨਾਫ਼ਾ', risk: 'ਖ਼ਤਰਾ', estimatedData: 'ਸਾਰੇ ਅੰਕੜੇ ਮੰਡੀ ਅਤੇ ਸਟੋਰੇਜ ਦੇ ਅੰਦਾਜ਼ਨ ਡੇਟਾ ਅਨੁਸਾਰ ਹਨ।', matchingBuyers: 'ਮਿਲਦੇ ਖਰੀਦਦਾਰ', noMatchingBuyers: 'ਕੋਈ ਖਰੀਦਦਾਰ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।', proposeTransaction: 'ਸੌਦਾ ਪੇਸ਼ ਕਰੋ', proposing: 'ਪੇਸ਼ਕਸ਼ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…', alreadySold: 'ਫ਼ਸਲ ਵਿਕ ਚੁੱਕੀ ਹੈ', processingOpportunities: 'ਪ੍ਰੋਸੈਸਿੰਗ ਮੌਕੇ', noProcessingCrop: 'ਇਸ ਫ਼ਸਲ ਲਈ ਪ੍ਰੋਸੈਸਿੰਗ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।', inputQuantity: 'ਇਨਪੁਟ ਮਾਤਰਾ', expectedOutput: 'ਸੰਭਾਵਿਤ ਆਉਟਪੁਟ', estimatedRevenue: 'ਅੰਦਾਜ਼ਨ ਆਮਦਨ', potentialProfitLabel: 'ਸੰਭਾਵਿਤ ਮੁਨਾਫ਼ਾ',
    marketPrices: 'ਮੰਡੀ ਭਾਅ', useMyLocation: 'ਮੇਰਾ ਸਥਾਨ ਵਰਤੋਂ', findingLocation: 'ਸਥਾਨ ਲੱਭਿਆ ਜਾ ਰਿਹਾ ਹੈ…', livePriceNote: 'ਲਾਈਵ ਮੰਡੀ ਭਾਅ AGMARKNET ਤੋਂ ਲਏ ਗਏ ਹਨ।', humidity: 'ਨਮੀ', wind: 'ਹਵਾ', noPriceData: 'ਇਸ ਫ਼ਸਲ ਲਈ ਕੋਈ ਭਾਅ ਨਹੀਂ ਮਿਲਿਆ।', mandiRateFeed: 'ਲਾਈਵ ਮੰਡੀ ਰੇਟ', live: 'ਲਾਈਵ', demo: 'ਡੈਮੋ', marketColumn: 'ਮੰਡੀ', distance: 'ਦੂਰੀ', currentPrice: 'ਮੌਜੂਦਾ ਭਾਅ', previousPrice: 'ਪਿਛਲਾ ਭਾਅ', change: 'ਬਦਲਾਅ', demand: 'ਮੰਗ',
    buyersTitle: 'ਖਰੀਦਦਾਰ ਮਾਰਕੀਟ', buyerNote: 'ਕਿਸਾਨਾਂ ਲਈ ਖਰੀਦਦਾਰਾਂ ਦੀ ਸੂਚੀ।', noBuyers: 'ਅਜੇ ਕੋਈ ਖਰੀਦਦਾਰ ਨਹੀਂ ਹੈ।', lookingFor: 'ਚਾਹੀਦਾ ਹੈ', upTo: 'ਤੱਕ',
    storageTitle: 'ਸਟੋਰੇਜ ਲੱਭੋ', storageNote: 'ਨੇੜਲੀਆਂ ਕੋਲਡ ਸਟੋਰੇਜ ਸੁਵਿਧਾਵਾਂ।', noStorage: 'ਸਟੋਰੇਜ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।', suitableFor: 'ਢੁਕਵੀਂ ਫ਼ਸਲ', available: 'ਮੌਜੂਦ', away: 'ਦੂਰ',
    processingTitle: 'ਪ੍ਰੋਸੈਸਿੰਗ ਇਕਾਈਆਂ', processingNote: 'ਫ਼ਸਲ ਪ੍ਰੋਸੈਸਿੰਗ ਕੇਂਦਰ।', noProcessing: 'ਕੋਈ ਪ੍ਰੋਸੈਸਿੰਗ ਇਕਾਈ ਨਹੀਂ ਮਿਲੀ।', processingCost: 'ਪ੍ਰੋਸੈਸਿੰਗ ਖ਼ਰਚਾ',
    askAgriFlow: 'AgriFlow ਨੂੰ ਪੁੱਛੋ', tryAsking: 'ਪੁੱਛ ਕੇ ਵੇਖੋ:', aiResponse: 'AI ਉੱਤਰ', quickAnswer: 'ਤੁਰੰਤ ਉੱਤਰ', thinking: 'ਸੋਚ ਰਿਹਾ ਹੈ…', send: 'ਭੇਜੋ', askQuestion: 'ਸਵਾਲ ਪੁੱਛੋ', responseLanguage: 'ਭਾਸ਼ਾ',
    analyticsOverview: 'ਵਿਸ਼ਲੇਸ਼ਣ', farmNumbers: 'ਤੁਹਾਡਾ ਖੇਤ, ਅੰਕੜਿਆਂ ਵਿੱਚ', analyticsIntro: 'ਆਪਣੀ ਫ਼ਸਲ ਅਤੇ ਮੁਨਾਫ਼ੇ ਦਾ ਵੇਰਵਾ ਵੇਖੋ।', liveActivity: 'ਸਰਗਰਮੀ', wastageAvoided: 'ਬਚਾਈ ਗਈ ਫ਼ਸਲ', valueProtected: 'ਸੁਰੱਖਿਅਤ ਮੁੱਲ', transactions: 'ਲੈਣ-ਦੇਣ', completedProposals: 'ਮੁਕੰਮਲ ਸੌਦੇ', transactionValue: 'ਲੈਣ-ਦੇਣ ਮੁੱਲ', totalRealized: 'ਕੁੱਲ ਪ੍ਰਾਪਤ ਮੁੱਲ', farmStory: 'ਖੇਤੀ ਵਿਸ਼ਲੇਸ਼ਣ', analyticsEmpty: 'ਡੇਟਾ ਦੇਖਣ ਲਈ ਉਪਜ ਸ਼ਾਮਲ ਕਰੋ।', low: 'ਘੱਟ', medium: 'ਦਰਮਿਆਨਾ', high: 'ਜ਼ਿਆਦਾ', dashboardNextAction: 'ਅਗਲਾ ਕਦਮ ਚੁਣੋ।',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'ਸਥਾਨ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।', locationDenied: 'ਸਥਾਨ ਦੀ ਆਗਿਆ ਨਹੀਂ ਮਿਲੀ।', weatherUnavailable: 'ਮੌਸਮ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ।',
    autoDetectRegion: 'ਸਵੈ-ਚਾਲਿਤ (ਖੇਤਰ ਅਨੁਸਾਰ)', regionDetected: 'ਪਛਾਣਿਆ ਖੇਤਰ',
  },
  mr: {
    dashboard: 'डॅशबोर्ड', produce: 'पीक', market: 'बाजार', buyers: 'खरेदीदार', buyerPortal: 'खरेदीदार पोर्टल', storage: 'गोदाम', processing: 'प्रक्रिया', assistant: 'सल्लागार', analytics: 'विश्लेषण',
    farmerWorkspace: 'शेतकरी कार्यक्षेत्र', logout: 'लॉग आउट', closeMenu: 'मेनू बंद करा', openMenu: 'मेनू उघडा',
    farmerOverview: 'शेतकरी आढावा', goodToSeeYou: 'नमस्कार', dashboardIntro: 'तुमच्या पिकाचे आणि उत्पन्नाचे संपूर्ण तपशील.', harvestIntelligence: 'पीक माहिती', harvestTagline: 'आजच्या पिकातून उद्याचा योग्य निर्णय घ्या.',
    nextAction: 'पुढे काय करावे?', totalProduce: 'एकूण पीक', estimatedValue: 'अंदाजे मूल्य', potentialProfit: 'संभाव्य नफा', wastageRisk: 'नासाडीचा धोका', activeRecommendations: 'सक्रिय शिफारसी', availableBuyers: 'उपलब्ध खरेदीदार', yourProduce: 'तुमचे पीक', addProduce: 'पीक जोडा', viewAll: 'सर्व पहा', noProduce: 'तुम्ही अद्याप कोणतेही पीक जोडलेले नाही.', entriesOnRecord: 'नोंदी उपलब्ध आहेत.',
    loading: 'लोड होत आहे…', loadingProduce: 'पीक लोड होत आहे…', addProduceTitle: 'पीक जोडा', editProduce: 'पीक संपादित करा', crop: 'पीक', quantity: 'प्रमाण', unit: 'एकक', quality: 'दर्जा', harvestDate: 'काढणी तारीख', location: 'स्थान', expectedSellDate: 'अपेक्षित विक्री तारीख', optional: 'पर्यायी', saveChanges: 'बदल जतन करा', saving: 'जतन करत आहे…', addFirstEntry: 'पहिली नोंद करा →', viewEdit: 'पहा / संपादित करा', getRecommendation: 'शिफारस मिळवा', findBuyers: 'खरेदीदार शोधा', processingOptions: 'प्रक्रिया पर्याय', delete: 'हटवा', deleteConfirm: 'हे पीक हटवायचे का?', harvested: 'काढणी', backToProduce: 'पिकावर परत जा', recommendation: 'शिफारस', recommendedAction: 'शिफारस केलेली कृती', score: 'स्कोअर', profit: 'नफा', risk: 'धोका', estimatedData: 'सर्व आकडे अंदाजित बाजार माहितीवर आधारित आहेत.', matchingBuyers: 'योग्य खरेदीदार', noMatchingBuyers: 'सध्या कोणताही खरेदीदार उपलब्ध नाही.', proposeTransaction: 'प्रस्ताव पाठवा', proposing: 'पाठवत आहे…', alreadySold: 'पीक विकले गेले आहे', processingOpportunities: 'प्रक्रिया संधी', noProcessingCrop: 'या पिकासाठी प्रक्रिया उपलब्ध नाही.', inputQuantity: 'प्रमाण', expectedOutput: 'अंदाजे उत्पादन', estimatedRevenue: 'अंदाजे उत्पन्न', potentialProfitLabel: 'संभाव्य नफा',
    marketPrices: 'बाजार भाव', useMyLocation: 'माझे स्थान वापरा', findingLocation: 'स्थान शोधत आहे…', livePriceNote: 'थेट बाजारभाव AGMARKNET कडून घेतले आहेत.', humidity: 'आद्रता', wind: 'वारा', noPriceData: 'या पिकासाठी भाव उपलब्ध नाहीत.', mandiRateFeed: 'थेट बाजारभाव', live: 'थेट', demo: 'डेमो', marketColumn: 'बाजार', distance: 'अंतर', currentPrice: 'चालू भाव', previousPrice: 'मागील भाव', change: 'बदल', demand: 'मागणी',
    buyersTitle: 'खरेदीदार बाजार', buyerNote: 'शेतकऱ्यांसाठी खरेदीदार यादी.', noBuyers: 'सध्या खरेदीदार उपलब्ध नाहीत.', lookingFor: 'हवे आहे', upTo: 'पर्यंत',
    storageTitle: 'गोदाम शोधा', storageNote: 'जवळपासची शीतगृहे आणि गोदामे.', noStorage: 'गोदाम उपलब्ध नाही.', suitableFor: 'योग्य पिके', available: 'उपलब्ध', away: 'लांब',
    processingTitle: 'प्रक्रिया उद्योग', processingNote: 'अन्न प्रक्रिया केंद्रे.', noProcessing: 'प्रक्रिया केंद्र उपलब्ध नाही.', processingCost: 'प्रक्रिया खर्च',
    askAgriFlow: 'AgriFlow ला विचारा', tryAsking: 'विचारून पहा:', aiResponse: 'AI उत्तर', quickAnswer: 'त्वरित उत्तर', thinking: 'विचार करत आहे…', send: 'पाठवा', askQuestion: 'प्रश्न विचारा', responseLanguage: 'भाषा',
    analyticsOverview: 'कामगिरी आढावा', farmNumbers: 'तुमची शेती, आकड्यांमध्ये', analyticsIntro: 'पिकाचे मूल्य आणि नफा तपासा.', liveActivity: 'थेट हालचाली', wastageAvoided: 'वाचवलेली नासाडी', valueProtected: 'संरक्षित मूल्य', transactions: 'व्यवहार', completedProposals: 'पूर्ण व्यवहार', transactionValue: 'व्यवहार मूल्य', totalRealized: 'एकूण मिळालेले मूल्य', farmStory: 'शेती यशोगाथा', analyticsEmpty: 'आलेख पाहण्यासाठी पीक जोडा.', low: 'कमी', medium: 'मध्यम', high: 'जास्त', dashboardNextAction: 'योग्य निर्णय घ्या.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'स्थान उपलब्ध नाही.', locationDenied: 'परवानगी नाकारली.', weatherUnavailable: 'हवामान लोड होऊ शकले नाही.',
    autoDetectRegion: 'स्वयं-शोध (प्रदेशानुसार)', regionDetected: 'ओळखलेला प्रदेश',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ', produce: 'પાક', market: 'બજાર', buyers: 'ખરીદદાર', buyerPortal: 'ખરીદદાર પોર્ટલ', storage: 'સંગ્રહ', processing: 'પ્રોસેસિંગ', assistant: 'સહાયક', analytics: 'વિશ્લેષણ',
    farmerWorkspace: 'ખેડૂત કાર્યક્ષેત્ર', logout: 'લૉગ આઉટ', closeMenu: 'મેનુ બંધ કરો', openMenu: 'મેનુ ખોલો',
    farmerOverview: 'ખેડૂત વિહંગાવલોકન', goodToSeeYou: 'નમસ્તે', dashboardIntro: 'તમારા પાક અને ઉત્પાદનની સંપૂર્ણ માહિતી.', harvestIntelligence: 'પાક માહિતી', harvestTagline: 'આજના પાકથી આવતીકાલનો યોગ્ય નિર્ણય લો.',
    nextAction: 'હવે શું કરવું જોઈએ?', totalProduce: 'કુલ પાક', estimatedValue: 'અંદાજિત મૂલ્ય', potentialProfit: 'સંભવિત નફો', wastageRisk: 'બગાડનું જોખમ', activeRecommendations: 'સક્રિય ભલામણો', availableBuyers: 'ઉપલબ્ધ ખરીદદારો', yourProduce: 'તમારો પાક', addProduce: 'પાક ઉમેરો', viewAll: 'બધું જુઓ', noProduce: 'તમે હજુ સુધી કોઈ પાક ઉમેર્યો નથી.', entriesOnRecord: 'નોંધણીઓ ઉપલબ્ધ છે.',
    loading: 'લોડ થઈ રહ્યું છે…', loadingProduce: 'પાક લોડ થઈ રહ્યો છે…', addProduceTitle: 'પાક ઉમેરો', editProduce: 'પાક સુધારો', crop: 'પાક', quantity: 'જથ્થો', unit: 'એકમ', quality: 'ગુણવત્તા', harvestDate: 'કાપણી તારીખ', location: 'સ્થળ', expectedSellDate: 'વેચાણ તારીખ', optional: 'વૈકલ્પિક', saveChanges: 'ફેરફારો સાચવો', saving: 'સાચવી રહ્યું છે…', addFirstEntry: 'પ્રથમ પાક ઉમેરો →', viewEdit: 'જુઓ / સુધારો', getRecommendation: 'ભલામણ મેળવો', findBuyers: 'ખરીદદાર શોધો', processingOptions: 'પ્રોસેસિંગ વિકલ્પો', delete: 'કાઢી નાખો', deleteConfirm: 'શું આ પાક કાઢી નાખવો છે?', harvested: 'કાપણી', backToProduce: 'પાક પર પાછા જાઓ', recommendation: 'ભલામણ', recommendedAction: 'ભલામણ કરેલ પગલું', score: 'સ્કોર', profit: 'નફો', risk: 'જોખમ', estimatedData: 'બધા આંકડા અંદાજિત બજાર માહિતી પર આધારિત છે.', matchingBuyers: 'સુસંગત ખરીદદારો', noMatchingBuyers: 'કોઈ ખરીદદાર ઉપલબ્ધ નથી.', proposeTransaction: 'સોદો પ્રસ્તાવિત કરો', proposing: 'પ્રસ્તાવ મોકલી રહ્યા છીએ…', alreadySold: 'પાક વેચાઈ ગયો છે', processingOpportunities: 'પ્રોસેસિંગ તકો', noProcessingCrop: 'આ પાક માટે પ્રોસેસિંગ ઉપલબ્ધ નથી.', inputQuantity: 'જથ્થો', expectedOutput: 'અંદાજિત ઉત્પાદન', estimatedRevenue: 'અંદાજિત આવક', potentialProfitLabel: 'સંભવિત નફો',
    marketPrices: 'બજાર ભાવ', useMyLocation: 'મારું સ્થાન વાપરો', findingLocation: 'સ્થાન શોધી રહ્યું છે…', livePriceNote: 'જીવંત ભાવ AGMARKNET તરફથી લેવામાં આવ્યા છે.', humidity: 'ભેજ', wind: 'પવન', noPriceData: 'આ પાક માટે કોઈ ભાવ મળ્યા નથી.', mandiRateFeed: 'જીવંત મંડી ભાવ', live: 'લાઇવ', demo: 'ડેમો', marketColumn: 'મંડી', distance: 'અંતર', currentPrice: 'હાલનો ભાવ', previousPrice: 'પાછલો ભાવ', change: 'ફેરફાર', demand: 'માંગ',
    buyersTitle: 'ખરીદદાર બજાર', buyerNote: 'ખેડૂતો માટે ખરીદદાર યાદી.', noBuyers: 'કોઈ ખરીદદાર ઉપલબ્ધ નથી.', lookingFor: 'જરૂર છે', upTo: 'સુધી',
    storageTitle: 'કોલ્ડ સ્ટોરેજ શોધો', storageNote: 'નજીકના કોલ્ડ સ્ટોરેજ અને વેરહાઉસ.', noStorage: 'સ્ટોરેજ ઉપલબ્ધ નથી.', suitableFor: 'યોગ્ય પાક', available: 'ઉપલબ્ધ', away: 'દૂર',
    processingTitle: 'પ્રોસેસિંગ એકમો', processingNote: 'ખાદ્ય પ્રોસેસિંગ કેન્દ્રો.', noProcessing: 'કોઈ પ્રોસેસિંગ એકમ મળ્યું નથી.', processingCost: 'પ્રોસેસિંગ ખર્ચ',
    askAgriFlow: 'AgriFlow ને પૂછો', tryAsking: 'પૂછી જુઓ:', aiResponse: 'AI ઉત્તર', quickAnswer: 'ઝડપી જવાબ', thinking: 'વિચારી રહ્યું છે…', send: 'મોકલો', askQuestion: 'પ્રશ્ન પૂછો', responseLanguage: 'ભાષા',
    analyticsOverview: 'વિશ્લેષણ', farmNumbers: 'તમારું ખેતર, આંકડાઓમાં', analyticsIntro: 'ઉત્પાદન અને નફાની સમીક્ષા કરો.', liveActivity: 'પ્રવૃત્તિ', wastageAvoided: 'બચાવેલ બગાડ', valueProtected: 'રક્ષિત મૂલ્ય', transactions: 'સોદાઓ', completedProposals: 'પૂર્ણ સોદાઓ', transactionValue: 'સોદા મૂલ્ય', totalRealized: 'કુલ પ્રાપ્ત મૂલ્ય', farmStory: 'ખેતી સમીક્ષા', analyticsEmpty: 'ગ્રાફ જોવા માટે પાક ઉમેરો.', low: 'ઓછું', medium: 'મધ્યમ', high: 'વધારે', dashboardNextAction: 'આગળનું પગલું પસંદ કરો.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'સ્થાન ઉપલબ્ધ નથી.', locationDenied: 'પરવાનગી નકારી.', weatherUnavailable: 'હવામાન લોડ થઈ શક્યું નથી.',
    autoDetectRegion: 'ઓટો-ડિટેક્ટ (પ્રદેશ મુજબ)', regionDetected: 'ઓળખાયેલ પ્રદેશ',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్', produce: 'పంట', market: 'మార్కెట్', buyers: 'కొనుగోలుదారులు', buyerPortal: 'బయ్యర్ పోర్టల్', storage: 'నిల్వ', processing: 'ప్రాసెసింగ్', assistant: 'సహాయకుడు', analytics: 'విశ్లేషణ',
    farmerWorkspace: 'రైతు కార్యక్షేత్రం', logout: 'లాగ్ అవుట్', closeMenu: 'మెనూ మూసివేయి', openMenu: 'మెనూ తెరవండి',
    farmerOverview: 'రైతు సారాంశం', goodToSeeYou: 'నమస్కారం', dashboardIntro: 'మీ పంట మరియు దిగుబడి పూర్తి వివరాలు.', harvestIntelligence: 'పంట సమాచారం', harvestTagline: 'నేటి పంటతో రేపటి మెరుగైన నిర్ణయం తీసుకోండి.',
    nextAction: 'తర్వాత ఏమి చేయాలి?', totalProduce: 'మొత్తం పంట', estimatedValue: 'అంచనా విలువ', potentialProfit: 'సంభావ్య లాభం', wastageRisk: 'నష్టం ప్రమాదం', activeRecommendations: 'యాక్టివ్ సిఫార్సులు', availableBuyers: 'అందుబాటులో ఉన్న కొనుగోలుదారులు', yourProduce: 'మీ పంట', addProduce: 'పంట జోడించండి', viewAll: 'అన్నీ చూడండి', noProduce: 'మీరు ఇంకా ఏ పంటను జోడించలేదు.', entriesOnRecord: 'నమోదులు ఉన్నాయి.',
    loading: 'లోడ్ అవుతోంది…', loadingProduce: 'పంట వివరాలు లోడ్ అవుతున్నాయి…', addProduceTitle: 'పంట జోడించండి', editProduce: 'పంటను సవరించండి', crop: 'పంట', quantity: 'పరిమాణం', unit: 'యూనిట్', quality: 'నాణ్యత', harvestDate: 'కోత తేదీ', location: 'ప్రాంతం', expectedSellDate: 'అమ్మకపు తేదీ', optional: 'ఐచ్ఛికం', saveChanges: 'మార్పులను సేవ్ చేయండి', saving: 'సేవ్ అవుతోంది…', addFirstEntry: 'మొదటి పంట నమోదు చేయండి →', viewEdit: 'చూడండి / సవరించండి', getRecommendation: 'సిఫార్సు పొందండి', findBuyers: 'కొనుగోలుదారులను కనుగొనండి', processingOptions: 'ప్రాసెసింగ్ ఎంపికలు', delete: 'తొలగించండి', deleteConfirm: 'ఈ పంటను తొలగించాలా?', harvested: 'కోత పూర్తయింది', backToProduce: 'పంట పేజీకి వెళ్లండి', recommendation: 'సిఫార్సు', recommendedAction: 'సిఫార్సు చేసిన చర్య', score: 'స్కోరు', profit: 'లాభం', risk: 'ప్రమాదం', estimatedData: 'అన్ని గణాంకాలు మార్కెట్ సమాచారం ఆధారంగా అంచనా వేయబడ్డాయి.', matchingBuyers: 'సరిపోలే కొనుగోలుదారులు', noMatchingBuyers: 'కొనుగోలుదారులు అందుబాటులో లేరు.', proposeTransaction: 'లావాదేవీ ప్రతిపాదించండి', proposing: 'ప్రతిపాదిస్తోంది…', alreadySold: 'పంట అమ్ముడైంది', processingOpportunities: 'ప్రాసెసింగ్ అవకాశాలు', noProcessingCrop: 'ఈ పంటకు ప్రాసెసింగ్ అందుబాటులో లేదు.', inputQuantity: 'పరిమాణం', expectedOutput: 'అంచనా ఉత్పత్తి', estimatedRevenue: 'అంచనా రాబడి', potentialProfitLabel: 'సంభావ్య లాభం',
    marketPrices: 'మార్కెట్ ధరలు', useMyLocation: 'నా స్థానాన్ని వాడండి', findingLocation: 'స్థానాన్ని శోధిస్తోంది…', livePriceNote: 'ప్రత్యక్ష ధరలు AGMARKNET నుండి తీసుకోబడ్డాయి.', humidity: 'తేమ', wind: 'గాలి', noPriceData: 'ఈ పంటకు ధరలు లేవు.', mandiRateFeed: 'లైవ్ మార్కెట్ రేట్లు', live: 'లైవ్', demo: 'డెమో', marketColumn: 'మార్కెట్', distance: 'దూరం', currentPrice: 'ప్రస్తుత ధర', previousPrice: 'మునుపటి ధర', change: 'మార్పు', demand: 'డిమాండ్',
    buyersTitle: 'కొనుగోలుదారుల మార్కెట్', buyerNote: 'రైతుల కోసం కొనుగోలుదారుల జాబితా.', noBuyers: 'కొనుగోలుదారులు అందుబాటులో లేరు.', lookingFor: 'కావాలి', upTo: 'వరకు',
    storageTitle: 'నిల్వ కేంద్రాలు', storageNote: 'సమీపంలోని శీతల గిడ్డంగులు.', noStorage: 'నిల్వ సౌకర్యం అందుబాటులో లేదు.', suitableFor: 'అనుకూలమైన పంటలు', available: 'అందుబాటులో ఉంది', away: 'దూరం',
    processingTitle: 'ప్రాసెసింగ్ యూనిట్లు', processingNote: 'ఆహార ప్రాసెసింగ్ కేంద్రాలు.', noProcessing: 'ప్రాసెసింగ్ యూనిట్లు అందుబాటులో లేవు.', processingCost: 'ప్రాసెసింగ్ ఖర్చు',
    askAgriFlow: 'AgriFlow ను అడగండి', tryAsking: 'ఇలా అడగండి:', aiResponse: 'AI సమాధానం', quickAnswer: 'త్వరిత సమాధానం', thinking: 'ఆలోచిస్తోంది…', send: 'పంపు', askQuestion: 'ప్రశ్న అడగండి', responseLanguage: 'భాష',
    analyticsOverview: 'విశ్లేషణ', farmNumbers: 'మీ వ్యవసాయం, సంఖ్యలలో', analyticsIntro: 'దిగుబడి మరియు లాభాలను పరిశీలించండి.', liveActivity: 'కార్యకలాపాలు', wastageAvoided: 'నివారించిన వృథా', valueProtected: 'రక్షిత విలువ', transactions: 'లావాదేవీలు', completedProposals: 'పూర్తయిన లావాదేవీలు', transactionValue: 'లావాదేవీ విలువ', totalRealized: 'మొత్తం పొందిన విలువ', farmStory: 'వ్యవసాయ విశ్లేషణ', analyticsEmpty: 'గ్రాఫ్ చూడటానికి పంటను జోడించండి.', low: 'తక్కువ', medium: 'మధ్యస్థం', high: 'ఎక్కువ', dashboardNextAction: 'సరైన నిర్ణయం తీసుకోండి.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'లొకేషన్ అందుబాటులో లేదు.', locationDenied: 'అనుమతి నిరాకరించబడింది.', weatherUnavailable: 'వాతావరణం లోడ్ కాలేదు.',
    autoDetectRegion: 'ఆటో-డిటెక్ట్ (ప్రాంతం ప్రకారం)', regionDetected: 'గుర్తించబడిన ప్రాంతం',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு', produce: 'பயிர்', market: 'சந்தை', buyers: 'வாங்குவோர்', buyerPortal: 'வாங்குவோர் போர்டல்', storage: 'சேமிப்பு', processing: 'செயலாக்கம்', assistant: 'உதவியாளர்', analytics: 'பகுப்பாய்வு',
    farmerWorkspace: 'விவசாயி பணியிடம்', logout: 'வெளியேறு', closeMenu: 'மெனுவை மூடு', openMenu: 'மெனுவை திற',
    farmerOverview: 'விவசாயி கண்ணோட்டம்', goodToSeeYou: 'வணக்கம்', dashboardIntro: 'உங்கள் பயிர் மற்றும் மகசூல் பற்றிய முழு விவரங்கள்.', harvestIntelligence: 'பயிர் நுண்ணறிவு', harvestTagline: 'இன்றைய அறுவடையை நாளைய சிறந்த முடிவாக மாற்றுங்கள்.',
    nextAction: 'அடுத்து என்ன செய்ய வேண்டும்?', totalProduce: 'மொத்த பயிர்', estimatedValue: 'மதிப்பிடப்பட்ட மதிப்பு', potentialProfit: 'சாத்தியமான லாபம்', wastageRisk: 'வீணாகும் அபாயம்', activeRecommendations: 'செயலில் உள்ள பரிந்துரைகள்', availableBuyers: 'உள்ள வாங்குவோர்', yourProduce: 'உங்கள் பயிர்', addProduce: 'பயிர் சேர்', viewAll: 'அனைத்தும் பார்', noProduce: 'நீங்கள் இன்னும் எந்த பயிரையும் சேர்க்கவில்லை.', entriesOnRecord: 'பதிவுகள் உள்ளன.',
    loading: 'ஏற்றுகிறது…', loadingProduce: 'பயிர் விவரங்கள் ஏற்றப்படுகின்றன…', addProduceTitle: 'பயிர் சேர்க்கவும்', editProduce: 'பயிரைத் திருத்தவும்', crop: 'பயிர்', quantity: 'அளவு', unit: 'அலகு', quality: 'தரம்', harvestDate: 'அறுவடை தேதி', location: 'இடம்', expectedSellDate: 'விற்பனை தேதி', optional: 'விருப்பமானது', saveChanges: 'மாற்றங்களை சேமி', saving: 'சேமிக்கிறது…', addFirstEntry: 'முதல் பயிரைச் சேர்க்கவும் →', viewEdit: 'பார் / திருத்து', getRecommendation: 'பரிந்துரை பெறுக', findBuyers: 'வாங்குவோரைக் கண்டறியவும்', processingOptions: 'செயலாக்க விருப்பங்கள்', delete: 'நீக்கு', deleteConfirm: 'இந்த பயிரை நீக்கவா?', harvested: 'அறுவடை செய்யப்பட்டது', backToProduce: 'பயிருக்குத் திரும்பு', recommendation: 'பரிந்துரை', recommendedAction: 'பரிந்துரைக்கப்பட்ட நடவடிக்கை', score: 'மதிப்பெண்', profit: 'லாபம்', risk: 'அபாயம்', estimatedData: 'அனைத்து புள்ளிவிவரங்களும் மதிப்பிடப்பட்டவை.', matchingBuyers: 'பொருந்தும் வாங்குவோர்', noMatchingBuyers: 'வாங்குவோர் இல்லை.', proposeTransaction: 'பரிவர்த்தனையை முன்மொழியவும்', proposing: 'முன்மொழிகிறது…', alreadySold: 'பயிர் விற்கப்பட்டது', processingOpportunities: 'செயலாக்க வாய்ப்புகள்', noProcessingCrop: 'செயலாக்கம் கிடைக்கவில்லை.', inputQuantity: 'உள்ளீட்டு அளவு', expectedOutput: 'எதிர்பார்க்கப்படும் வெளியீடு', estimatedRevenue: 'மதிப்பிடப்பட்ட வருவாய்', potentialProfitLabel: 'சாத்தியமான லாபம்',
    marketPrices: 'சந்தை விலைகள்', useMyLocation: 'என் இருப்பிடத்தைப் பயன்படுத்து', findingLocation: 'இருப்பிடத்தைத் தேடுகிறது…', livePriceNote: 'நேரடி விலைகள் AGMARKNET இலிருந்து பெறப்படுகின்றன.', humidity: 'ஈரப்பதம்', wind: 'காற்று', noPriceData: 'விலை விவரங்கள் இல்லை.', mandiRateFeed: 'நேரடி மண்டி விலை', live: 'நேரலை', demo: 'டெமோ', marketColumn: 'சந்தை', distance: 'தூரம்', currentPrice: 'தற்போதைய விலை', previousPrice: 'முந்தைய விலை', change: 'மாற்றம்', demand: 'தேவை',
    buyersTitle: 'வாங்குவோர் சந்தை', buyerNote: 'விவசாயிகளுக்கான வாங்குவோர் பட்டியல்.', noBuyers: 'வாங்குவோர் இல்லை.', lookingFor: 'தேவைப்படுகிறது', upTo: 'வரை',
    storageTitle: 'சேமிப்பகத்தைக் கண்டறி', storageNote: 'அருகிலுள்ள குளிர்சாதனக் கிடங்குகள்.', noStorage: 'சேமிப்பகம் இல்லை.', suitableFor: 'பொருத்தமான பயிர்கள்', available: 'உள்ளது', away: 'தூரம்',
    processingTitle: 'செயலாக்க அலகுகள்', processingNote: 'உணவு பதப்படுத்தும் மையங்கள்.', noProcessing: 'செயலாக்க அலகுகள் இல்லை.', processingCost: 'செயலாக்க செலவு',
    askAgriFlow: 'AgriFlow விடம் கேளுங்கள்', tryAsking: 'கேட்டுப் பாருங்கள்:', aiResponse: 'AI பதில்', quickAnswer: 'விரைவான பதில்', thinking: 'யோசிக்கிறது…', send: 'அனுப்பு', askQuestion: 'கேள்வி கேட்கவும்', responseLanguage: 'மொழி',
    analyticsOverview: 'செயல்திறன் கண்ணோட்டம்', farmNumbers: 'உங்கள் விவசாயம், எண்களில்', analyticsIntro: 'மதிப்பு மற்றும் லாபத்தைப் பகுப்பாய்வு செய்யுங்கள்.', liveActivity: 'நடவடிக்கைகள்', wastageAvoided: 'தவிர்க்கப்பட்ட இழப்பு', valueProtected: 'பாதுகாக்கப்பட்ட மதிப்பு', transactions: 'பரிவர்த்தனைகள்', completedProposals: 'முடிந்த ஒப்பந்தங்கள்', transactionValue: 'பரிவர்த்தனை மதிப்பு', totalRealized: 'மொத்த வருவாய்', farmStory: 'விவசாயப் பகுப்பாய்வு', analyticsEmpty: 'விவரங்களைக் காண பயிரைச் சேர்க்கவும்.', low: 'குறைவு', medium: 'நடுத்தரம்', high: 'அதிகம்', dashboardNextAction: 'சரியான முடிவை எடுக்கவும்.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'இருப்பிடம் கிடைக்கவில்லை.', locationDenied: 'அனுமதி மறுக்கப்பட்டது.', weatherUnavailable: 'வானிலை ஏற்ற முடியவில்லை.',
    autoDetectRegion: 'தானியங்கு (பகுதிப்படி)', regionDetected: 'கண்டறியப்பட்ட பகுதி',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড', produce: 'ফসল', market: 'বাজার', buyers: 'ক্রেতা', buyerPortal: 'ক্রেতা পোর্টাল', storage: 'গুদাম', processing: 'প্রক্রিয়াকরণ', assistant: 'সহায়ক', analytics: 'বিশ্লেষণ',
    farmerWorkspace: 'কৃষক কর্মক্ষেত্র', logout: 'লগ আউট', closeMenu: 'মেনু বন্ধ করুন', openMenu: 'মেনু খুলুন',
    farmerOverview: 'কৃষক সারসংক্ষেপ', goodToSeeYou: 'নমস্কার', dashboardIntro: 'আপনার ফসল ও ফলনের সম্পূর্ণ বিবরণ।', harvestIntelligence: 'ফসল তথ্য', harvestTagline: 'আজকের ফসল থেকে আগামীকালের সঠিক সিদ্ধান্ত নিন।',
    nextAction: 'এরপর কী করা উচিত?', totalProduce: 'মোট ফসল', estimatedValue: 'আনুমানিক মূল্য', potentialProfit: 'সম্ভাব্য লাভ', wastageRisk: 'নষ্ট হওয়ার ঝুঁকি', activeRecommendations: 'সক্রিয় পরামর্শ', availableBuyers: 'উপলব্ধ ক্রেতা', yourProduce: 'আপনার ফসল', addProduce: 'ফসল যোগ করুন', viewAll: 'সব দেখুন', noProduce: 'আপনি এখনও কোনো ফসল যোগ করেননি।', entriesOnRecord: 'নথিভুক্ত রয়েছে।',
    loading: 'লোড হচ্ছে…', loadingProduce: 'ফসল লোড হচ্ছে…', addProduceTitle: 'ফসল যোগ করুন', editProduce: 'ফসল সম্পাদনা করুন', crop: 'ফসল', quantity: 'পরিমাণ', unit: 'একক', quality: 'গুণমান', harvestDate: 'কাটার তারিখ', location: 'স্থান', expectedSellDate: 'বিক্রির তারিখ', optional: 'ঐচ্ছিক', saveChanges: 'পরিবর্তন সংরক্ষণ করুন', saving: 'সংরক্ষণ হচ্ছে…', addFirstEntry: 'প্রথম ফসল যোগ করুন →', viewEdit: 'দেখুন / সম্পাদনা', getRecommendation: 'পরামর্শ পান', findBuyers: 'ক্রেতা খুঁজুন', processingOptions: 'প্রক্রিয়াকরণ বিকল্প', delete: 'মুছুন', deleteConfirm: 'এই ফসলটি মুছে ফেলতে চান?', harvested: 'কাটা হয়েছে', backToProduce: 'ফসলে ফিরে যান', recommendation: 'পরামর্শ', recommendedAction: 'সুপারিশকৃত পদক্ষেপ', score: 'স্কোর', profit: 'লাভ', risk: 'ঝুঁকি', estimatedData: 'সমস্ত পরিসংখ্যান আনুমানিক বাজার তথ্যের উপর ভিত্তি করে।', matchingBuyers: 'উপযুক্ত ক্রেতা', noMatchingBuyers: 'কোনো ক্রেতা পাওয়া যায়নি।', proposeTransaction: 'প্রস্তাব পাঠান', proposing: 'পাঠানো হচ্ছে…', alreadySold: 'ফসল বিক্রি হয়ে গেছে', processingOpportunities: 'প্রক্রিয়াকরণের সুযোগ', noProcessingCrop: 'এই ফসলের প্রক্রিয়াকরণ উপলব্ধ নেই।', inputQuantity: 'পরিমাণ', expectedOutput: 'প্রত্যাশিত উৎপাদন', estimatedRevenue: 'আনুমানিক আয়', potentialProfitLabel: 'সম্ভাব্য লাভ',
    marketPrices: 'বাজার দর', useMyLocation: 'আমার অবস্থান ব্যবহার করুন', findingLocation: 'অবস্থান খোঁজা হচ্ছে…', livePriceNote: 'সরাসরি দর AGMARKNET থেকে সংগৃহীত।', humidity: 'আর্দ্রতা', wind: 'বাতাস', noPriceData: 'এই ফসলের দর পাওয়া যায়নি।', mandiRateFeed: 'সরাসরি মান্ডি দর', live: 'লাইভ', demo: 'ডেমো', marketColumn: 'মান্ডি', distance: 'দূরত্ব', currentPrice: 'বর্তমান দর', previousPrice: 'পূর্বের দর', change: 'পরিবর্তন', demand: 'চাহিদা',
    buyersTitle: 'ক্রেতা বাজার', buyerNote: 'কৃষকদের জন্য ক্রেতাদের তালিকা।', noBuyers: 'কোনো ক্রেতা উপলব্ধ নেই।', lookingFor: 'প্রয়োজন', upTo: 'পর্যন্ত',
    storageTitle: 'হিমাগার খুঁজুন', storageNote: 'নিকটবর্তী কোল্ড স্টোরেজ ও গুদাম।', noStorage: 'গুদাম উপলব্ধ নেই।', suitableFor: 'উপযুক্ত ফসল', available: 'উপলব্ধ', away: 'দূরে',
    processingTitle: 'প্রক্রিয়াকরণ কেন্দ্র', processingNote: 'খাদ্য প্রক্রিয়াকরণ কারখানা।', noProcessing: 'কোনো প্রক্রিয়াকরণ কেন্দ্র নেই।', processingCost: 'প্রক্রিয়াকরণ খরচ',
    askAgriFlow: 'AgriFlow-কে জিজ্ঞাসা করুন', tryAsking: 'জিজ্ঞাসা করে দেখুন:', aiResponse: 'AI উত্তর', quickAnswer: 'দ্রুত উত্তর', thinking: 'ভাবছে…', send: 'পাঠান', askQuestion: 'প্রশ্ন করুন', responseLanguage: 'ভাষা',
    analyticsOverview: 'কর্মক্ষমতা পর্যালোচনা', farmNumbers: 'আপনার খামার, সংখ্যায়', analyticsIntro: 'ফলন এবং লাভের হিসাব দেখুন।', liveActivity: 'কার্যক্রম', wastageAvoided: 'সংরক্ষিত ফসল', valueProtected: 'সুরক্ষিত মূল্য', transactions: 'লেনদেন', completedProposals: 'সম্পূর্ণ লেনদেন', transactionValue: 'লেনদেন মূল্য', totalRealized: 'মোট প্রাপ্ত মূল্য', farmStory: 'কৃষি বিশ্লেষণ', analyticsEmpty: 'গ্রাফ দেখতে ফসল যোগ করুন।', low: 'কম', medium: 'মাঝারি', high: 'বেশি', dashboardNextAction: 'সঠিক সিদ্ধান্ত নিন।',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'অবস্থান পাওয়া যায়নি।', locationDenied: 'অনুমতি মেলেনি।', weatherUnavailable: 'আবহাওয়া লোড করা যায়নি।',
    autoDetectRegion: 'স্বয়ংক্রিয় (অঞ্চল অনুযায়ী)', regionDetected: 'সনাক্ত অঞ্চল',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', produce: 'ಬೆಳೆ', market: 'ಮಾರುಕಟ್ಟೆ', buyers: 'ಖರೀದಿದಾರರು', buyerPortal: 'ಖರೀದಿದಾರರ ಪೋರ್ಟಲ್', storage: 'ಶೇಖರಣೆ', processing: 'ಸಂಸ್ಕರಣೆ', assistant: 'ಸಹಾಯಕ', analytics: 'ವಿಶ್ಲೇಷಣೆ',
    farmerWorkspace: 'ರೈತ ಕಾರ್ಯಕ್ಷೇತ್ರ', logout: 'ಲಾಗ್ ಔಟ್', closeMenu: 'ಮೆನು ಮುಚ್ಚಿ', openMenu: 'ಮೆನು ತೆರೆಯಿರಿ',
    farmerOverview: 'ರೈತರ ವಿವರ', goodToSeeYou: 'ನಮಸ್ಕಾರ', dashboardIntro: 'ನಿಮ್ಮ ಬೆಳೆ ಮತ್ತು ಇಳುವರಿಯ ಸಂಪೂರ್ಣ ಮಾಹಿತಿ.', harvestIntelligence: 'ಬೆಳೆ ಮಾಹಿತಿ', harvestTagline: 'ಇಂದಿನ ಸುಗ್ಗಿಯಿಂದ ನಾಳಿನ ಉತ್ತಮ ನಿರ್ಧಾರ ಕೈಗೊಳ್ಳಿ.',
    nextAction: 'ಮುಂದೆ ಏನು ಮಾಡಬೇಕು?', totalProduce: 'ಒಟ್ಟು ಬೆಳೆ', estimatedValue: 'ಅಂದಾಜು ಮೌಲ್ಯ', potentialProfit: 'ಸಂಭಾವ್ಯ ಲಾಭ', wastageRisk: 'ನಷ್ಟದ ಅಪಾಯ', activeRecommendations: 'ಸಕ್ರಿಯ ಶಿಫಾರಸುಗಳು', availableBuyers: 'ಲಭ್ಯವಿರುವ ಖರೀದಿದಾರರು', yourProduce: 'ನಿಮ್ಮ ಬೆಳೆ', addProduce: 'ಬೆಳೆ ಸೇರಿಸಿ', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ', noProduce: 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಬೆಳೆಯನ್ನು ಸೇರಿಸಿಲ್ಲ.', entriesOnRecord: 'ದಾಖಲೆಗಳು ಲಭ್ಯವಿವೆ.',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…', loadingProduce: 'ಬೆಳೆ ವಿವರಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ…', addProduceTitle: 'ಬೆಳೆ ಸೇರಿಸಿ', editProduce: 'ಬೆಳೆ ತಿದ್ದುಪಡಿ', crop: 'ಬೆಳೆ', quantity: 'ಪ್ರಮಾಣ', unit: 'ಘಟಕ', quality: 'ಗುಣಮಟ್ಟ', harvestDate: 'ಕೊಯ್ಲು ದಿನಾಂಕ', location: 'ಸ್ಥಳ', expectedSellDate: 'ಮಾರಾಟ ದಿನಾಂಕ', optional: 'ಐಚ್ಛಿಕ', saveChanges: 'ಬದಲಾವಣೆ ಉಳಿಸಿ', saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…', addFirstEntry: 'ಮೊದಲ ಬೆಳೆ ಸೇರಿಸಿ →', viewEdit: 'ನೋಡಿ / ತಿದ್ದುಪಡಿ', getRecommendation: 'ಶಿಫಾರಸು ಪಡೆಯಿರಿ', findBuyers: 'ಖರೀದಿದಾರರನ್ನು ಹುಡುಕಿ', processingOptions: 'ಸಂಸ್ಕರಣಾ ಆಯ್ಕೆಗಳು', delete: 'ಅಳಿಸಿ', deleteConfirm: 'ಈ ಬೆಳೆಯನ್ನು ಅಳಿಸಬೇಕೇ?', harvested: 'ಕೊಯ್ಲು ಮಾಡಲಾಗಿದೆ', backToProduce: 'ಬೆಳೆ ಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ', recommendation: 'ಶಿಫಾರಸು', recommendedAction: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ', score: 'ಅಂಕ', profit: 'ಲಾಭ', risk: 'ಅಪಾಯ', estimatedData: 'ಎಲ್ಲಾ ಅಂಕಿಅಂಶಗಳು ಅಂದಾಜಿಸಲಾಗಿದೆ.', matchingBuyers: 'ಹೊಂದಾಣಿಕೆಯಾಗುವ ಖರೀದಿದಾರರು', noMatchingBuyers: 'ಯಾವುದೇ ಖರೀದಿದಾರರು ಲಭ್ಯವಿಲ್ಲ.', proposeTransaction: 'ವಹಿವಾಟು ಪ್ರಸ್ತಾಪಿಸಿ', proposing: 'ಪ್ರಸ್ತಾಪಿಸಲಾಗುತ್ತಿದೆ…', alreadySold: 'ಬೆಳೆ ಮಾರಾಟವಾಗಿದೆ', processingOpportunities: 'ಸಂಸ್ಕರಣಾ ಅವಕಾಶಗಳು', noProcessingCrop: 'ಸಂಸ್ಕರಣೆ ಲಭ್ಯವಿಲ್ಲ.', inputQuantity: 'ಪ್ರಮಾಣ', expectedOutput: 'ನಿರೀಕ್ಷಿತ ಇಳುವರಿ', estimatedRevenue: 'ಅಂದಾಜು ಆದಾಯ', potentialProfitLabel: 'ಸಂಭಾವ್ಯ ಲಾಭ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು', useMyLocation: 'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ', findingLocation: 'ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ…', livePriceNote: 'ಲೈವ್ ದರಗಳನ್ನು AGMARKNET ನಿಂದ ಪಡೆಯಲಾಗಿದೆ.', humidity: 'ತೇವಾಂಶ', wind: 'ಗಾಳಿ', noPriceData: 'ದರಗಳು ಲಭ್ಯವಿಲ್ಲ.', mandiRateFeed: 'ಲೈವ್ ಮಾರುಕಟ್ಟೆ ದರ', live: 'ಲೈವ್', demo: 'ಡೆಮೊ', marketColumn: 'ಮಾರುಕಟ್ಟೆ', distance: 'ದೂರ', currentPrice: 'ಪ್ರಸ್ತುತ ಬೆಲೆ', previousPrice: 'ಹಿಂದಿನ ಬೆಲೆ', change: 'ಬದಲಾವಣೆ', demand: 'ಬೇಡಿಕೆ',
    buyersTitle: 'ಖರೀದಿದಾರರ ಮಾರುಕಟ್ಟೆ', buyerNote: 'ರೈತರಿಗಾಗಿ ಖರೀದಿದಾರರ ಪಟ್ಟಿ.', noBuyers: 'ಖರೀದಿದಾರರು ಲಭ್ಯವಿಲ್ಲ.', lookingFor: 'ಬೇಕಾಗಿದೆ', upTo: 'ವರೆಗೆ',
    storageTitle: 'ಶೀತಲ ಗೋದಾಮು ಹುಡುಕಿ', storageNote: 'ಹತ್ತಿರದ ಗೋದಾಮುಗಳು.', noStorage: 'ಶೇಖರಣಾ ಸೌಲಭ್ಯ ಲಭ್ಯವಿಲ್ಲ.', suitableFor: 'ಸೂಕ್ತ ಬೆಳೆಗಳು', available: 'ಲಭ್ಯವಿದೆ', away: 'ದೂರ',
    processingTitle: 'ಸಂಸ್ಕರಣಾ ಘಟಕಗಳು', processingNote: 'ಆಹಾರ ಸಂಸ್ಕರಣಾ ಕೇಂದ್ರಗಳು.', noProcessing: 'ಯಾವುದೇ ಸಂಸ್ಕರಣಾ ಘಟಕವಿಲ್ಲ.', processingCost: 'ಸಂಸ್ಕರಣಾ ವೆಚ್ಚ',
    askAgriFlow: 'AgriFlow ಅನ್ನು ಕೇಳಿ', tryAsking: 'ಹೀಗೆ ಕೇಳಿ:', aiResponse: 'AI ಉತ್ತರ', quickAnswer: 'ತ್ವರಿತ ಉತ್ತರ', thinking: 'ಯೋಚಿಸುತ್ತಿದೆ…', send: 'ಕಳುಹಿಸಿ', askQuestion: 'ಪ್ರಶ್ನೆ ಕೇಳಿ', responseLanguage: 'ಭಾಷೆ',
    analyticsOverview: 'ವಿಶ್ಲೇಷಣೆ', farmNumbers: 'ನಿಮ್ಮ ಕೃಷಿ, ಅಂಕಿಗಳಲ್ಲಿ', analyticsIntro: 'ಇಳುವರಿ ಮತ್ತು ಲಾಭವನ್ನು ಪರಿಶೀಲಿಸಿ.', liveActivity: 'ಚಟುವಟಿಕೆಗಳು', wastageAvoided: 'ತಪ್ಪಿಸಲಾದ ನಷ್ಟ', valueProtected: 'ರಕ್ಷಿತ ಮೌಲ್ಯ', transactions: 'ವಹಿವಾಟುಗಳು', completedProposals: 'ಪೂರ್ಣಗೊಂಡ ವ್ಯವಹಾರಗಳು', transactionValue: 'ವಹಿವಾಟು ಮೌಲ್ಯ', totalRealized: 'ಒಟ್ಟು ಗಳಿಸಿದ ಮೌಲ್ಯ', farmStory: 'ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ', analyticsEmpty: 'ಗ್ರಾಫ್ ನೋಡಲು ಬೆಳೆ ಸೇರಿಸಿ.', low: 'ಕಡಿಮೆ', medium: 'ಮಧ್ಯಮ', high: 'ಹೆಚ್ಚು', dashboardNextAction: 'ಉತ್ತಮ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಿ.',
    languageEnglish: 'English', languageHindi: 'ಹಿन्दी', locationUnavailable: 'ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ.', locationDenied: 'ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ.', weatherUnavailable: 'ಹವಾಮಾನ ಲೋಡ್ ಆಗಲಿಲ್ಲ.',
    autoDetectRegion: 'ಸ್ವಯಂಚಾಲಿತ (ಪ್ರದೇಶದ ಪ್ರಕಾರ)', regionDetected: 'ಗುರುತಿಸಲಾದ ಪ್ರದೇಶ',
  },
} as const

export function translate(language: Language, key: TranslationKey): string {
  const dict = (translations as Record<string, Record<string, string>>)[language]
  if (dict && dict[key]) {
    return dict[key]
  }
  return (translations.hi as Record<string, string>)[key] || translations.en[key] || ''
}

export type { TranslationKey }
