export type Language = 'en' | 'hi'

type TranslationKey = keyof typeof translations.en

const translations = {
  en: {
    dashboard: 'Dashboard', produce: 'Produce', market: 'Market', buyers: 'Buyers', storage: 'Storage', processing: 'Processing', assistant: 'Assistant', analytics: 'Analytics',
    farmerWorkspace: 'FARMER WORKSPACE', logout: 'Log out', closeMenu: 'Close menu', openMenu: 'Open menu',
    farmerOverview: 'Farmer overview', goodToSeeYou: 'Good to see you', dashboardIntro: 'A clear view of what your harvest can do next.', harvestIntelligence: 'Harvest intelligence', harvestTagline: "Turn today's harvest into tomorrow's stronger decision.",
    nextAction: 'What should you do next?', totalProduce: 'Total Produce', estimatedValue: 'Estimated Value', potentialProfit: 'Potential Profit', wastageRisk: 'Wastage Risk', activeRecommendations: 'Active Recommendations', availableBuyers: 'Available Buyers', yourProduce: 'Your Produce', addProduce: 'Add produce', viewAll: 'View all', noProduce: "You haven't added any produce yet.", entriesOnRecord: 'entries on record.',
    loading: 'Loading…', loadingProduce: 'Loading your produce…', addProduceTitle: 'Add Produce', editProduce: 'Edit Produce', crop: 'Crop', quantity: 'Quantity', unit: 'Unit', quality: 'Quality', harvestDate: 'Harvest date', location: 'Location', expectedSellDate: 'Expected selling date', optional: 'optional', saveChanges: 'Save changes', saving: 'Saving…', addFirstEntry: 'Add your first entry →', viewEdit: 'View / Edit', getRecommendation: 'Get Recommendation', findBuyers: 'Find Buyers', processingOptions: 'Processing Options', delete: 'Delete', deleteConfirm: 'Delete this produce entry?', harvested: 'Harvested', backToProduce: 'Back to Produce', recommendation: 'Recommendation', recommendedAction: 'Recommended Action', score: 'Score', profit: 'Profit', risk: 'Risk', estimatedData: 'All figures are estimated from demo market, storage, processing, and buyer data — not live prices.', matchingBuyers: 'Matching Buyers', noMatchingBuyers: 'No buyers currently want this much of this crop.', proposeTransaction: 'Propose Transaction', proposing: 'Proposing…', alreadySold: 'Produce already sold', processingOpportunities: 'Processing Opportunities', noProcessingCrop: 'No processing units accept this crop yet.', inputQuantity: 'Input Quantity', expectedOutput: 'Expected Output', estimatedRevenue: 'Estimated Revenue', potentialProfitLabel: 'Potential Profit',
    marketPrices: 'Market Prices', useMyLocation: 'Use my location', findingLocation: 'Finding location…', livePriceNote: 'Live prices are sourced from AGMARKNET when configured; demo rows are labelled below.', humidity: 'Humidity', wind: 'Wind', noPriceData: 'No price data for this crop yet.', mandiRateFeed: 'Mandi rate feed', live: 'Live', demo: 'Demo', marketColumn: 'Market', distance: 'Distance', currentPrice: 'Current Price', previousPrice: 'Previous Price', change: 'Change', demand: 'Demand',
    buyersTitle: 'Buyer Marketplace', buyerNote: 'Demo buyer postings for hackathon demonstration.', noBuyers: 'No buyer postings yet.', lookingFor: 'Looking for', upTo: 'Up to',
    storageTitle: 'Storage Finder', storageNote: 'Demo storage facilities for hackathon demonstration.', noStorage: 'No storage facilities available.', suitableFor: 'Suitable for', available: 'available', away: 'away',
    processingTitle: 'Turn Produce into Value', processingNote: 'Demo processing units for hackathon demonstration.', noProcessing: 'No processing units available.', processingCost: 'processing cost',
    askAgriFlow: 'Ask AgriFlow', tryAsking: 'Try asking:', aiResponse: 'AI response', quickAnswer: 'Quick answer', thinking: 'Thinking…', send: 'Send', askQuestion: 'Ask a question', responseLanguage: 'Response language',
    analyticsOverview: 'Performance overview', farmNumbers: 'Your farm, in numbers', analyticsIntro: 'See where value is being created across your produce, prices, and transactions.', liveActivity: 'Live from your activity', wastageAvoided: 'Wastage avoided', valueProtected: 'Value protected', transactions: 'Transactions', completedProposals: 'Completed proposals', transactionValue: 'Transaction value', totalRealized: 'Total realized value', farmStory: 'Your farm story starts here', analyticsEmpty: 'Add produce and check its recommendations to start seeing charts here.', low: 'Low', medium: 'Medium', high: 'High', dashboardNextAction: 'Check your recommendations to decide your next move.',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'Location access is not available in this browser.', locationDenied: 'Location permission was denied. You can enable it in browser settings.', weatherUnavailable: 'Could not load weather for your location.',
  },
  hi: {
    dashboard: 'डैशबोर्ड', produce: 'उपज', market: 'बाज़ार', buyers: 'खरीदार', storage: 'भंडारण', processing: 'प्रसंस्करण', assistant: 'सहायक', analytics: 'विश्लेषण',
    farmerWorkspace: 'किसान कार्यक्षेत्र', logout: 'लॉग आउट', closeMenu: 'मेनू बंद करें', openMenu: 'मेनू खोलें',
    farmerOverview: 'किसान अवलोकन', goodToSeeYou: 'आपको देखकर अच्छा लगा', dashboardIntro: 'आपकी फसल के अगले कदम की स्पष्ट जानकारी।', harvestIntelligence: 'फसल की जानकारी', harvestTagline: 'आज की फसल से कल का बेहतर निर्णय लें।',
    nextAction: 'अब आपको क्या करना चाहिए?', totalProduce: 'कुल उपज', estimatedValue: 'अनुमानित मूल्य', potentialProfit: 'संभावित लाभ', wastageRisk: 'बर्बादी का जोखिम', activeRecommendations: 'सक्रिय सुझाव', availableBuyers: 'उपलब्ध खरीदार', yourProduce: 'आपकी उपज', addProduce: 'उपज जोड़ें', viewAll: 'सभी देखें', noProduce: 'आपने अभी तक कोई उपज नहीं जोड़ी है।', entriesOnRecord: 'प्रविष्टियां दर्ज हैं।',
    loading: 'लोड हो रहा है…', loadingProduce: 'आपकी उपज लोड हो रही है…', addProduceTitle: 'उपज जोड़ें', editProduce: 'उपज संपादित करें', crop: 'फसल', quantity: 'मात्रा', unit: 'इकाई', quality: 'गुणवत्ता', harvestDate: 'कटाई की तारीख', location: 'स्थान', expectedSellDate: 'अपेक्षित बिक्री तारीख', optional: 'वैकल्पिक', saveChanges: 'बदलाव सहेजें', saving: 'सहेज रहे हैं…', addFirstEntry: 'पहली प्रविष्टि जोड़ें →', viewEdit: 'देखें / संपादित करें', getRecommendation: 'सुझाव पाएं', findBuyers: 'खरीदार खोजें', processingOptions: 'प्रसंस्करण विकल्प', delete: 'हटाएं', deleteConfirm: 'क्या यह उपज प्रविष्टि हटानी है?', harvested: 'कटाई', backToProduce: 'उपज पर वापस जाएं', recommendation: 'सुझाव', recommendedAction: 'अनुशंसित कार्रवाई', score: 'स्कोर', profit: 'लाभ', risk: 'जोखिम', estimatedData: 'सभी आंकड़े डेमो बाज़ार, भंडारण, प्रसंस्करण और खरीदार डेटा से अनुमानित हैं, लाइव भाव नहीं।', matchingBuyers: 'मिलान वाले खरीदार', noMatchingBuyers: 'अभी कोई खरीदार इस फसल की इतनी मात्रा नहीं चाहता।', proposeTransaction: 'लेनदेन प्रस्तावित करें', proposing: 'प्रस्ताव भेज रहे हैं…', alreadySold: 'उपज पहले ही बिक चुकी है', processingOpportunities: 'प्रसंस्करण अवसर', noProcessingCrop: 'अभी कोई प्रसंस्करण इकाई इस फसल को स्वीकार नहीं करती।', inputQuantity: 'इनपुट मात्रा', expectedOutput: 'अनुमानित आउटपुट', estimatedRevenue: 'अनुमानित आय', potentialProfitLabel: 'संभावित लाभ',
    marketPrices: 'बाज़ार भाव', useMyLocation: 'मेरा स्थान इस्तेमाल करें', findingLocation: 'स्थान खोज रहे हैं…', livePriceNote: 'लाइव भाव उपलब्ध होने पर AGMARKNET से लिए जाते हैं; डेमो भाव नीचे बताए गए हैं।', humidity: 'नमी', wind: 'हवा', noPriceData: 'इस फसल के लिए अभी भाव उपलब्ध नहीं हैं।', mandiRateFeed: 'मंडी भाव', live: 'लाइव', demo: 'डेमो', marketColumn: 'बाज़ार', distance: 'दूरी', currentPrice: 'वर्तमान भाव', previousPrice: 'पिछला भाव', change: 'बदलाव', demand: 'मांग',
    buyersTitle: 'खरीदार बाज़ार', buyerNote: 'प्रदर्शन के लिए डेमो खरीदार पोस्टिंग।', noBuyers: 'अभी कोई खरीदार पोस्टिंग नहीं है।', lookingFor: 'चाहिए', upTo: 'अधिकतम',
    storageTitle: 'भंडारण खोजें', storageNote: 'प्रदर्शन के लिए डेमो भंडारण सुविधाएं।', noStorage: 'भंडारण सुविधा उपलब्ध नहीं है।', suitableFor: 'उपयुक्त फसलें', available: 'उपलब्ध', away: 'दूर',
    processingTitle: 'उपज से मूल्य बनाएं', processingNote: 'प्रदर्शन के लिए डेमो प्रसंस्करण इकाइयां।', noProcessing: 'प्रसंस्करण इकाई उपलब्ध नहीं है।', processingCost: 'प्रसंस्करण लागत',
    askAgriFlow: 'AgriFlow से पूछें', tryAsking: 'पूछकर देखें:', aiResponse: 'AI उत्तर', quickAnswer: 'त्वरित उत्तर', thinking: 'सोच रहे हैं…', send: 'भेजें', askQuestion: 'सवाल पूछें', responseLanguage: 'उत्तर की भाषा',
    analyticsOverview: 'प्रदर्शन अवलोकन', farmNumbers: 'आपका खेत, आंकड़ों में', analyticsIntro: 'अपनी उपज, भाव और लेनदेन से बन रहे मूल्य को देखें।', liveActivity: 'आपकी गतिविधि से लाइव', wastageAvoided: 'बर्बादी से बचाया', valueProtected: 'सुरक्षित मूल्य', transactions: 'लेनदेन', completedProposals: 'पूरे प्रस्ताव', transactionValue: 'लेनदेन मूल्य', totalRealized: 'कुल प्राप्त मूल्य', farmStory: 'आपके खेत की कहानी यहां से शुरू होती है', analyticsEmpty: 'चार्ट देखने के लिए उपज जोड़ें और उसके सुझाव देखें।', low: 'कम', medium: 'मध्यम', high: 'अधिक', dashboardNextAction: 'अपने अगले कदम का निर्णय लेने के लिए सुझाव देखें।',
    languageEnglish: 'English', languageHindi: 'हिन्दी', locationUnavailable: 'इस ब्राउज़र में स्थान सुविधा उपलब्ध नहीं है।', locationDenied: 'स्थान की अनुमति नहीं मिली। इसे ब्राउज़र सेटिंग्स में चालू करें।', weatherUnavailable: 'आपके स्थान का मौसम लोड नहीं हो सका।',
  },
} as const

export function translate(language: Language, key: TranslationKey): string {
  return translations[language][key] || translations.en[key]
}

export type { TranslationKey }
